[tool.poetry]
name = "setup.py"
version = "0.1.0"
description = ""
authors = ["abersheeran <me@abersheeran.com>"]
readme = "README.md"
license = "Apache-2.0"

homepage = "https://github.com/abersheeran/setup.py"
repository = "https://github.com/abersheeran/setup.py"

classifiers=[
    "Programming Language :: Python :: 3",
]

packages = [
    { include = "example" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
flake8 = "*"
black = "^19.10b0"
pytest = "^5.4.3"

[tool.dephell.main]
from = { format = "poetry", path = "pyproject.toml" }
to = { format = "setuppy", path = "setup.py" }

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
