# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='mkdocs-version',
    version='0.1.5',
    description='Simple and easy-to-use mkdocs version based on git tags',
    python_requires='==3.*,>=3.6.0',
    project_urls={
        "homepage": "https://github.com/abersheeran/mkdocs-version",
        "repository": "https://github.com/abersheeran/mkdocs-version"
    },
    author='abersheeran',
    author_email='me@abersheeran.com',
    license='Apache-2.0',
    classifiers=['Programming Language :: Python :: 3'],
    entry_points={
        "console_scripts": ["mkdocs-version = mkdocs_version.commands:main"]
    },
    packages=['mkdocs_version'],
    package_dir={"": "."},
    package_data={},
    install_requires=['click==7.*,>=7.1.2'],
    extras_require={"dev": ["black", "flake8", "pytest==5.*,>=5.4.3"]},
)
